/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.1
 * Generated at: 2024-12-05 12:52:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import logica.Carrito;
import logica.User;
import logica.Ropa;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Map;

public final class detalleReporte_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1732398734994L));
    _jspx_dependants.put("/componentes/headerContent.jsp", Long.valueOf(1733345375207L));
    _jspx_dependants.put("/componentes/header.jsp", Long.valueOf(1733340871901L));
    _jspx_dependants.put("jar:file:/C:/Users/tobar/OneDrive/Escritorio/Proyecto/target/mavenproject1-1.0-SNAPSHOT/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664464278000L));
    _jspx_dependants.put("/componentes/head.jsp", Long.valueOf(1733345968910L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("logica.User");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("logica.Ropa");
    _jspx_imports_classes.add("logica.Carrito");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\"/>\n");
      out.write("    <title>KOBCOEE</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"logo-container\">\n");
      out.write("        <img src=\"img/png.png\" alt=\"Logo de KOBCOEE\" class=\"logo\">\n");
      out.write("        <h1 id=\"nombreEsq\">KOBCOEE</h1>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"container\">\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Detalle del Reporte</title>\n");
      out.write("    <style>\n");
      out.write("        /* Asegurarse de que html y body ocupen toda la altura de la página */\n");
      out.write("        html, body {\n");
      out.write("            height: 100%;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estructura del body para flexbox */\n");
      out.write("        body {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Asegurarse de que el contenido principal ocupe el espacio restante */\n");
      out.write("        .main-content {\n");
      out.write("            flex: 1;\n");
      out.write("            padding: 20px;\n");
      out.write("            overflow: auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estilo para el pie de página */\n");
      out.write("        footer {\n");
      out.write("            background-color: #2c3e50;\n");
      out.write("            color: white;\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 15px 0;\n");
      out.write("            width: 100%;\n");
      out.write("            margin-top: auto; /* Asegura que el footer se mantenga al final de la página */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        footer p {\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estilo de la tabla */\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table th, table td {\n");
      out.write("            padding: 10px;\n");
      out.write("            text-align: left;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table th {\n");
      out.write("            background-color: #f4f4f4;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estilo de los botones */\n");
      out.write("        button {\n");
      out.write("            background-color: #4CAF50;\n");
      out.write("            color: white;\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button:hover {\n");
      out.write("            background-color: #45a049;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Estilo del enlace de regreso */\n");
      out.write("        a {\n");
      out.write("            text-decoration: none;\n");
      out.write("            color: #2c3e50;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        a:hover {\n");
      out.write("            color: #4CAF50;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Opcional: Ajustes para el pre-formato del detalle de ventas */\n");
      out.write("        pre {\n");
      out.write("            white-space: pre-wrap;\n");
      out.write("            word-wrap: break-word;\n");
      out.write("            background-color: #f4f4f4;\n");
      out.write("            padding: 15px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/styles.css\">\n");
      out.write("<head>\n");
      out.write("    <style>\n");
      out.write("        .header-content {\n");
      out.write("        color: white; /* Asegúrate de que el texto sea legible */\n");
      out.write("        font-size: 3rem;\n");
      out.write("        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.7); /* Agrega sombra para mayor contraste */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .header-container {\n");
      out.write("        width: 100%;\n");
      out.write("        height: 400px;\n");
      out.write("        background: url('img/imagenfondo.jpg') no-repeat center center;\n");
      out.write("        background-size: cover; /* Para ajustar la imagen */\n");
      out.write("        display: flex;\n");
      out.write("        justify-content: center;\n");
      out.write("        align-items: center;\n");
      out.write("        position: relative;\n");
      out.write("    }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<html>\n");
      out.write("    <div class=\"header-container\">\n");
      out.write("        <div class=\"header-content\">\n");
      out.write("            <h1>KOBCOEE</h1>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\">\n");

    User currentUser = (User) session.getAttribute("currentUser");
    String role = "";
    if (currentUser != null) {
        role = currentUser.getRole();
    }
    Carrito carrito = (Carrito) session.getAttribute("carrito");
    double total = 0;
    if (carrito != null) {
        for (Map.Entry<Ropa, Integer> entry : carrito.getRopas().entrySet()) {
            total += entry.getKey().getPrecio() * entry.getValue(); 
        }
    }
    DecimalFormat df = new DecimalFormat("0.00");

      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("    <ul class=\"nav-menu\">\n");
      out.write("        <li><a href=\"index.jsp\">Inicio</a></li>\n");
      out.write("        <li><a href=\"https://www.instagram.com/kobcoee_/\">Instagram</a></li>\n");
      out.write("        <li><a href=\"mailto:coee1x1490@gmail.com\">Correo electrónico</a></li>\n");
      out.write("        <li><a href=\"acercaDe.jsp\">Acerca de</a></li>\n");
      out.write("           \n");
      out.write("        ");
 if (currentUser == null) { 
      out.write("\n");
      out.write("            <li><a href=\"login.jsp\">Iniciar Sesión</a></li>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 if (currentUser != null) { 
      out.write("\n");
      out.write("            <li><a href=\"LogoutServlet\">Cerrar Sesión</a></li>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </ul>\n");
      out.write("        \n");
      out.write("    <div class=\"nav-icons\">\n");
      out.write("        ");
 if (currentUser != null) { 
      out.write("\n");
      out.write("            <a href=\"detallesUsuario.jsp\">\n");
      out.write("            <img src=\"img/usuario.png\" alt=\"Usuario\" class=\"nav-logo\">\n");
      out.write("            </a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <img src=\"img/carrito.png\" alt=\"Carrito\" class=\"nav-logo\" onclick=\"toggleCart()\">\n");
      out.write("    </div>\n");
      out.write("    <div id=\"cartWindow\" class=\"cart-window\">\n");
      out.write("         <div class=\"cart-content\">\n");
      out.write("            <h2>Tu Carrito</h2>\n");
      out.write("            ");
 if (carrito != null && !carrito.getRopas().isEmpty()) { 
      out.write("\n");
      out.write("                <ul id=\"cartItems\">\n");
      out.write("                    ");
 
                        for (Map.Entry<Ropa, Integer> entry : carrito.getRopas().entrySet()) {
                            Ropa ropa = entry.getKey();
                            int quantity = entry.getValue();
                    
      out.write("\n");
      out.write("                        <li>\n");
      out.write("                            <img src=\"");
      out.print( ropa.getImagen() );
      out.write("\" alt=\"");
      out.print( ropa.getNombre() );
      out.write("\" width=\"50\">\n");
      out.write("                            ");
      out.print( ropa.getNombre() );
      out.write(" - Talla: ");
      out.print( ropa.getTalla() );
      out.write(" - Color: ");
      out.print( ropa.getColor() );
      out.write("<br>\n");
      out.write("                            Precio unitario: $");
      out.print( df.format(ropa.getPrecio()) );
      out.write("<br>\n");
      out.write("                            Cantidad: ");
      out.print( quantity );
      out.write("\n");
      out.write("                            <a href=\"EliminardelCarritoServlet?id=");
      out.print( ropa.getId() );
      out.write("\" class=\"eliminarProducto\">\n");
      out.write("                               <img src=\"img/x.png\" alt=\"Eliminar\" width=\"13\">\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </ul>\n");
      out.write("                <hr>\n");
      out.write("                <p><strong>Total: $");
      out.print( df.format(total) );
      out.write("</strong></p>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <p>Tu carrito está vacío.</p>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            <button onclick=\"window.location.href='venta.jsp'\">Ir a Comprar</button>\n");
      out.write("            <button id=\"cerrarCarrito\" onclick=\"toggleCart()\">Cerrar</button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function toggleCart() {\n");
      out.write("        var cartWindow = document.getElementById('cartWindow');\n");
      out.write("        cartWindow.classList.toggle('open');\n");
      out.write("    }\n");
      out.write("</script>");
      out.write("\n");
      out.write("    <div class=\"main-content\">\n");
      out.write("        <h2>Detalle del Reporte</h2>\n");
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("        <p><a href=\"GenerarReporteServlet\">Volver a Reportes Semanales</a></p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"clearfix\"></div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("            ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("            ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /detalleReporte.jsp(107,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty reporte}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                <table>\n");
        out.write("                    <tr>\n");
        out.write("                        <th>Fecha</th>\n");
        out.write("                        <td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fecha}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</td> \n");
        out.write("                    </tr>\n");
        out.write("                    <tr>\n");
        out.write("                        <th>Detalle de Ventas</th>\n");
        out.write("                        <td>\n");
        out.write("                            <pre>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reporte.detallesVentas}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</pre>\n");
        out.write("                        </td>\n");
        out.write("                    </tr>\n");
        out.write("                    <tr>\n");
        out.write("                        <th>Total Generado</th>\n");
        out.write("                        <td>$");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reporte.totalGenerado}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</td>\n");
        out.write("                    </tr>\n");
        out.write("                </table>\n");
        out.write("\n");
        out.write("                <form action=\"DetalleReporteServlet\" method=\"POST\">\n");
        out.write("                    <input type=\"hidden\" name=\"reporteId\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reporte.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\n");
        out.write("                    <button type=\"submit\">Generar PDF</button>\n");
        out.write("                </form>\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                <p>El reporte no está disponible o ocurrió un error.</p>\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
